# Generated by Django 2.2 on 2020-08-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200818_1540'),
        ('posts', '0003_auto_20200819_1250'),
    ]

    operations = [
    ]
